FROM blacktop/elasticsearch:5.6
LABEL Description="elasticsearch 5.6 whit analysis-ik" MAINTAINER=<xuanye.wan@gmail.com>
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v5.6.8/elasticsearch-analysis-ik-5.6.8.zip