version: '2'
services:
  mysql_master_1:
    image: mysql:5.7.16
    container_name: mysql_master_1
    volumes:
      - ../config/mysql-master1/:/etc/mysql/:ro    
      - ../config/hosts:/etc/hosts:ro
    ports:
      - "3309:3306"
    networks:
      mysql:
        ipv4_address: 172.18.0.2
    ulimits:
      nproc: 65535
    hostname: mysql_master_1
    mem_limit: 1024m
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=m1test
      - TZ=Asia/Shanghai
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
  mysql_slave_1:
      image: mysql:5.7.16
      container_name: mysql_slave_1
      volumes:
        - ../config/mysql-slave1/:/etc/mysql/:ro      
        - ../config/config/hosts:/etc/hosts:ro
      ports:
        - "3307:3306"
      networks:
        mysql:
          ipv4_address: 172.18.0.3
      links:
        - mysql_master_1
      ulimits:
        nproc: 65535
      hostname: mysql_slave_1
      mem_limit: 1024m
      restart: always
      environment:
        - MYSQL_ROOT_PASSWORD=s1test
        - TZ=Asia/Shanghai
      command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
  mysql_slave_2:
    image: mysql:5.7.16
    container_name: mysql_slave_2
    volumes:
      - ../config/mysql-slave2/:/etc/mysql/:ro     
      - ../config/hosts:/etc/hosts:ro
    ports:
      - "3308:3306"
    links:
      - mysql_master_1
    networks:
      mysql:
        ipv4_address: 172.18.0.4
    ulimits:
      nproc: 65535
    hostname: mysql_slave_2
    mem_limit: 1024m
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=s2test
      - TZ=Asia/Shanghai
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
  mycat:
    image: xuanye/mycat:1.6
    container_name: mycat
    volumes:
      - ../config/mycat/:/mycat/conf/:ro
      - ../config/mycat-logs/:/mycat/logs/:rw    
      - ../config/hosts:/etc/hosts:ro
    ports:
      - "8066:8066"
      - "9066:9066"
    links:
      - mysql_master_1
      - mysql_slave_1
      - mysql_slave_2
    networks:
      mysql:
        ipv4_address: 172.18.0.5
    ulimits:
      nproc: 65535
    hostname: mycat_1
    mem_limit: 1024m
    restart: always
networks:
  mysql:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.18.0.0/24
        gateway: 172.18.0.1
